name: CI
env:
  # Throughout the workflow, we build native build explicitly without using gradle task
  SKIP_NATIVE_BUILD: 1
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master
jobs:
  test:
    needs: build-native
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v2
    - name: modprobe tls
      run: sudo modprobe tls
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Restore native libs
      uses: actions/download-artifact@v2
      with:
        name: native-libs
        path: jktls/build/native
    - name: Execute test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build check
  build-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Use cross to build against old glibc
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --manifest-path native/Cargo.toml --target x86_64-unknown-linux-gnu
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --manifest-path native/Cargo.toml --target x86_64-unknown-linux-gnu --release
    - name: Copy native lib
      working-directory: ./jktls
      env:
        RUST_TARGET: x86_64-unknown-linux-gnu
      run: ../gradlew copyNativeLib
    - uses: actions/upload-artifact@v2
      with:
        name: native-libs
        path: jktls/build/native/*
        retention-days: 1
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Restore native libs
      uses: actions/download-artifact@v2
      with:
        name: native-libs
        path: jktls/build/native
    - id: get-tag-version
      run: |
        version=$(echo ${{github.ref}} | cut -f3 -d/ | sed 's/^v//')
        echo "::set-output name=version::$version"
    - name: Build universal jar
      working-directory: ./jktls
      run: ../gradlew -Pversion=${{ steps.get-tag-version.outputs.version }} -Psnapshot=false universalJar
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: jktls/build/libs/jktls-${{ steps.get-tag-version.outputs.version }}-universal.jar
        asset_name: jktls-${{ steps.get-tag-version.outputs.version }}-universal.jar
        asset_content_type: application/octet-stream
